github.com:
    git_protocol: https
    users:
        quang-megatron:
        harrylowkey:
        dung-megatron:
        hodfords-quang-th-backend:
    user: hodfords-quang-th-backend
omniyatgroup.ghe.com:
    git_protocol: ssh
    users:
        dang-quang:
    user: dang-quang
