k9s:
  cluster: arn:aws:eks:ap-southeast-1:276736272121:cluster/renyoo-dev-eks
  namespace:
    active: pixerlens-dev
    lockFavorites: false
    favorites:
    - pixerlens-client-dev
    - superset-dev
    - all
    - pixerlens-client-uat
    - database-uat
    - argocd
    - ingress-nginx
    - checker-dev
    - database-dev
    - pixerlens-uat
    - pixerlens-dev
    - default
    - rotex-dev
  view:
    active: pod
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
