k9s:
  cluster: arn:aws:eks:ap-southeast-1:276736272121:cluster/renyoo-dev-eks
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - pim-dev
      - vulnerability-dataverse-dev
      - database-dev
      - tool-uat
      - annotet-dev
      - minio-develop
      - pixerlens-uat
      - rotex-uat
  view:
    active: v1/pods all
  featureGates:
    nodeShell: false
  proxy: null
