k9s:
  cluster: arn:aws:eks:ap-southeast-1:276736272121:cluster/renyoo-dev-eks
  namespace:
    active: all
    lockFavorites: false
    favorites:
    - all
    - pixerlens-data-uat
    - pixerlens-data-dev
    - pixerpost
    - tool-uat
    - pim-dev
    - trisu-uat
    - database-uat
    - pim-prod
    - complaintmgm-uat
    - pixerlens-client-dev
    - keycloak-dev
    - database-dev
    - tool-dev
    - pim-uat
    - kube-system
    - pixerlens-client-uat
    - rotex-uat
    - rotex-dev
    - kube-public
    - kube-node-lease
    - keycloak-uat
    - cert-manager
    - checker-uat
    - system-dev
    - default
    - superset-dev
    - ingress-nginx
    - checker-dev
    - argocd
    - pixerlens-uat
    - micrologic-uat
    - pixerlens-mobile-demo
    - pixerlens-dev
  view:
    active: node
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
