#!/usr/bin/env sh

# stop process new window manager in Ventura
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist

# global settings
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xff60ff60
yabai -m config window_border_radius 0
yabai -m config window_border_blur           off

# Padding
yabai -m config \
	layout bsp \
	top_padding 0   \
	bottom_padding 26  \
	left_padding 0 \
	right_padding 0 \
	window_gap 6 \

# signals
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-index-jsx\"'"

# Rules

# Labels
yabai -m space 1 --label I
yabai -m space 2 --label II
yabai -m space 3 --label III
yabai -m space 4 --label IV
yabai -m space 5 --label V


# Devops
yabai -m rule --add app="^sqlectron$" opacity=1 manage=off space=I
yabai -m rule --add app="^Postman$" opacity=1 manage=off space=I
yabai -m rule --add app="Mingo$" opacity=1 manage=off space=I
yabai -m rule --add app="^Docker$" opacity=1 manage=off space=I
yabai -m rule --add app="^OrbStack$" opacity=1 manage=off space=I
yabai -m rule --add app="^Lens$" opacity=1 manage=off space=I
yabai -m rule --add app="^Apidog$" opacity=1 manage=off space=I
yabai -m rule --add app="^Postico$" opacity=1 manage=off space=I
yabai -m rule --add app="^RedisInsight-v2$" opacity=1 manage=off space=I
yabai -m rule --add app="^Flipper$" opacity=1 manage=off space=I
yabai -m rule --add app="^FileZilla$" opacity=1 manage=off space=I
yabai -m rule --add label="VirtualBox" app="^VirtualBox$" opacity=1 manage=off space=I

# Development
yabai -m rule --add app="Alacritty" space=II
yabai -m rule --add app="kitty" space=II
yabai -m rule --add app="Code" space=II manage=off
yabai -m rule --add app="WebStorm" space=II manage=off
yabai -m rule --add app="Emacs" space=II manage=off
yabai -m rule --add app="^Xcode$" space=II manage=off
yabai -m rule --add app="GitKraken" space=II manage=off
yabai -m rule --add app="Sourcetree" space=II manage=off

# View
yabai -m rule --add app="^Microsoft Edge$" space=III opacity=1 manage=off
yabai -m rule --add app="^Brave Browser$" space=III opacity=1 manage=off
yabai -m rule --add app="qutebrowser" space=III manage=off
yabai -m rule --add app="Safari" space=III opacity=1 manage=off
yabai -m rule --add app="^Figma$" space=III opacity=1 manage=off
yabai -m rule --add app="Notion" space=III opacity=1 manage=off
yabai -m rule --add app="Obsidian" space=III opacity=1 manage=off
yabai -m rule --add app="^Miro$" space=III opacity=1 manage=off
yabai -m rule --add app="StarUML" space=III opacity=1 manage=off
yabai -m rule --add app="EasyPlantUML" space=III opacity=1 manage=off
yabai -m rule --add app="draw.io" space=III opacity=1 manage=off
yabai -m rule --add app="WPS Office" space=III opacity=1 manage=off
yabai -m rule --add app="Linear" space=III opacity=1 manage=off

# Communication
yabai -m rule --add app="Slack" space=II opacity=1 manage=off
yabai -m rule --add app="zoom.us" space=IV opacity=1 manage=off
yabai -m rule --add app="^Microsoft Teams$" space=IV opacity=1 manage=off
yabai -m rule --add app="^Discord$" space=III opacity=1 manage=off
yabai -m rule --add app="^Skype$" space=IV opacity=1 manage=off
yabai -m rule --add app="^Mailspring$" space=IV opacity=1 manage=off
yabai -m rule --add app="^Microsoft Outlook$" space=IV opacity=1 manage=off
yabai -m rule --add app="Messenger" space=IV opacity=1 manage=off
yabai -m rule --add app="Mimestream" space=IV opacity=1 manage=off
yabai -m rule --add app="Telegram" space=IV opacity=1 manage=off

# Entertainment
yabai -m rule --add app="^Spotify$" space=V opacity=1 manage=off
yabai -m rule --add app="VLC" space=V manage=off

# Others
yabai -m rule --add app="QuickTime Player" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add label="Clean My Mac" app="^CleanMyMac X$" manage=off
yabai -m rule --add app="Finder" opacity=1 manage=off sticky=true
yabai -m rule --add app="^System Settings" manage=off opacity=1
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add app="^Notes$" opacity=1 manage=off
yabai -m rule --add app="Pages" opacity=1 manage=off
yabai -m rule --add app="^Preview" opacity=1 manage=off
yabai -m rule --add app="^Microsoft Word$" opacity=1 manage=off
yabai -m rule --add app="^Microsoft Excel$" opacity=1 manage=off
yabai -m rule --add app="^Microsoft PowerPoint$" opacity=1 manage=off
yabai -m rule --add app="Numi" opacity=1 manage=off
yabai -m rule --add app="Terminal" opacity=1 manage=off
yabai -m rule --add app="1Password" opacity=1 manage=off
yabai -m rule --add app="^DevUtils$" opacity=1 manage=off
yabai -m rule --add app="^Stats$" opacity=1 manage=off
yabai -m rule --add app="^Raycast$" opacity=1 manage=off
yabai -m rule --add app="^Skitch$" opacity=1 manage=off
yabai -m rule --add app="^DataGrip$" manage=off opacity=1
yabai -m rule --add app="^Zalo$" manage=off opacity=1 space=II


# show digital colour meter topmost and on all spaces
yabai -m rule --add app="^Digital Colou?r Meter$" sticky=on

echo "yabai configuration loaded.."

