k9s:
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  skipLatestRevCheck: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: k3d-ckad-cluster
  currentCluster: k3d-ckad-cluster
  clusters:
    arn:aws:eks:ap-southeast-1:276736272121:cluster/renyoo-dev-eks:
      namespace:
        active: pixerlens-client-dev
        lockFavorites: false
        favorites:
        - kube-system
        - all
        - default
      view:
        active: pod
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
        labels: {}
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /Users/harrydang/.config/k9s/screen-dumps/
  ui:
    enableMouse: true
    headless: false
    logoless: true
    skin: customize
    
